import './globals.css'
import { Inter } from 'next/font/google'
// React Query
import ReactQueryProvider from './components/ReactQueryProvider'
import ChakraConfigProvder from './components/ChakraConfigProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ReactQueryProvider>
      <html lang="en">
        <body className={inter.className}>
          <ChakraConfigProvder>{children}</ChakraConfigProvder>
        </body>
      </html>
    </ReactQueryProvider>
  );
}
