import "./globals.css"
import { Inter } from "next/font/google"
// React Query
import ChakraConfigProvder from "./components/providers/ChakraConfigProvider"
import ReactQueryProvider from "./components/providers/ReactQueryProvider"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ReactQueryProvider>
      <html lang="en">
        <body className={inter.className}>
          <ChakraConfigProvder>{children}</ChakraConfigProvder>
        </body>
      </html>
    </ReactQueryProvider>
  );
}
